#!/run/current-system/sw/bin/bash


SCRIPTSDIR=$HOME/.config/hypr/scripts

# polkit agent
if [[ ! 'pidof polkit-gnome-authentication-agent-1' ]];then
	/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi
